/* Shared copy for the static English/Chinese pages and interactive UI. */
const seoContent = {
  en: {
    hero_headline: '<span style="color:#D9A64A">ASA Resin Tiles</span> &amp; UPVC Roofing Sheets',
    hero_tagline: 'Manufactured in Foshan, China.<br>Custom roofing for distributors and projects.',
    nav_acc_cat: 'Accessories',
    about_li2: 'Roofing profiles for residential and industrial use',
    prod1_desc: 'Three-layer co-extrusion combines an ASA surface, PVC core and reinforced bottom layer. Choose a profile, thickness, color and length to suit your roofing project. Confirm the current technical drawing before ordering.',
    prod2_desc: 'UPVC corrugated sheets offer a lightweight roofing option for factories, warehouses, farms and carports. Discuss the profile, support spacing, climate and chemical exposure with our sales team before selecting a specification.',
    refs_2_meta: 'Color references and profile dimensions — confirm the specification for your selected model',
    refs_3_meta: 'Hollow-core structure, profile dimensions and matching accessories',
    spec_life: 'Service life', spec_life_value: 'Depends on specification and conditions',
    spec_fire_value: 'Request the model-specific test report',
    spec_weight2: 'Weight',
    why1_title: 'ASA Surface Layer', why1_desc: 'ASA is used as the exterior layer of our resin tiles. Ask for the technical data and weathering results applicable to your selected product.', why1_stat: 'Surface layer',
    why2_title: 'Project Specification Support', why2_desc: 'Tell us the standards required for your destination market. Confirm the applicable fire test report and product specification before placing an order.', why2_stat: 'Technical documents',
    why3_title: 'Production Planning', why3_desc: 'Confirm the product specification, quantity and target delivery date with our team so that production and shipment can be planned together.', why3_stat: 'Production lines',
    why4_title: 'Roofing System Details', why4_desc: 'Weather protection depends on the roof pitch, overlaps, fixings and installation. Request the installation details for the selected profile.', why4_stat: 'Installation details',
    why5_title: 'Custom Colors & OEM', why5_desc: 'Send your color reference, thickness, length and packaging requirements. Available options and sample approval are confirmed for each order.', why5_stat: 'Color matching',
    why6_title: 'Lightweight Roof Tiles', why6_desc: 'The listed ASA tile weight is 6–8 kg/m², depending on specification. Confirm the actual product weight and have the roof structure assessed for your project.', why6_stat: 'Per m²',
    acc5_desc: 'Protective caps for compatible roofing fasteners',
    order1_desc: 'Send the product, thickness, color, quantity, sheet length and destination port for a project quotation.',
    order2_desc: 'Confirm the drawings, samples, packaging, payment terms and shipping terms with our sales team.',
    order3_desc: 'Production starts according to the agreed order and payment terms. The confirmed schedule depends on quantity and customization.',
    order4_desc: 'Confirm the shipment, remaining payment and required export documents according to the agreed order terms.',
    contact_title: 'Request a Roofing Quote',
    fac1: 'Roofing Sheet Storage', fac2: 'Loading Roofing Sheets', fac3: 'Factory Operations', fac4: 'Packing & Dispatch',
    comparison_note: 'Material selection depends on the product, building design and local requirements. Compare current technical documents, installed cost and maintenance needs for your project.',
    compare_title: 'Choosing a Roofing Material',
    image_note: 'Roofing inspiration images illustrate design styles; they are not verified customer project references.',
    product_reference_note: 'Profile and color references. Confirm the selected model, dimensions and test documents with sales before ordering.',
    form_quantity: 'Estimated Quantity', form_color: 'Color / RAL Code', form_size: 'Roof Size / Sheet Length', form_port: 'Destination Port',
    applications_heading: 'Roofing Applications & Factory', applications_intro: 'Product options for residential, commercial, industrial and agricultural roofs.',
    applications_label: 'Application Scenarios', factory_label: 'Inside Our Foshan Factory',
    whatsapp_cta: 'Chat on WhatsApp', skip_main: 'Skip to main content'
  },
  zh: {
    hero_headline: '<span style="color:#D9A64A">ASA 合成树脂瓦</span>与 UPVC 波浪瓦',
    hero_tagline: '中国佛山制造。<br>服务经销商与工程采购，支持定制。',
    about_li2: '住宅及工业屋面产品瓦型',
    prod1_desc: '采用三层共挤结构，结合 ASA 表层、PVC 芯层和底层。可按屋面项目选择瓦型、厚度、颜色和长度，订货前请确认当前技术图纸。',
    prod2_desc: 'UPVC 波浪瓦为工厂、仓库、农场及车棚提供轻质屋面选择。选型前请与销售团队确认瓦型、支撑间距、气候和化学环境等要求。',
    refs_2_meta: '颜色参考与瓦型尺寸——请按选定型号确认规格',
    refs_3_meta: '中空结构、瓦型尺寸与配套辅材',
    spec_life_value: '取决于规格及使用条件', spec_fire_value: '请索取对应型号的检测报告', spec_weight2: '重量',
    why1_title: 'ASA 表层', why1_desc: '树脂瓦采用 ASA 外表层。请索取所选产品适用的技术资料和耐候测试结果。', why1_stat: '表层材料',
    why2_title: '工程规格支持', why2_desc: '请告知目的市场要求的标准，订货前确认适用的防火检测报告与产品规格。', why2_stat: '技术资料',
    why3_title: '生产计划', why3_desc: '与销售团队确认产品规格、数量及目标交货日期，以便安排生产和出货。', why3_stat: '条生产线',
    why4_title: '屋面系统细节', why4_desc: '防雨效果取决于屋面坡度、搭接、固定方式及施工质量。请索取选定瓦型的安装说明。', why4_stat: '安装细节',
    why5_title: '定制颜色与 OEM', why5_desc: '提供颜色参考、厚度、长度和包装要求，可用选项与样品确认按具体订单协商。', why5_stat: '颜色匹配',
    why6_title: '轻质屋面瓦', why6_desc: '所列 ASA 树脂瓦重量为每平方米 6–8 公斤，具体取决于规格。请确认实际产品重量，并按项目要求评估屋面结构。', why6_stat: '每平方米',
    acc5_desc: '适用于配套屋面紧固件的保护帽',
    order1_desc: '提供产品、厚度、颜色、数量、板长与目的港，以便准备工程报价。',
    order2_desc: '与销售团队确认图纸、样品、包装、付款方式和运输条款。',
    order3_desc: '按约定订单及付款条款安排生产，具体交期取决于数量和定制要求。',
    order4_desc: '按已确认的订单条款安排出运、剩余款项与所需出口单证。',
    contact_title: '屋面产品询价',
    fac1: '屋面板材仓储', fac2: '屋面板材装车', fac3: '工厂作业', fac4: '包装与发运',
    comparison_note: '材料选择取决于产品、建筑设计和当地要求。请结合当前技术资料、安装总成本与维护需求进行比较。',
    compare_title: '如何选择屋面材料',
    image_note: '屋面灵感图片仅用于展示设计风格，不代表已经核实的客户工程案例。',
    product_reference_note: '瓦型与颜色参考。订货前请向销售团队确认所选型号、尺寸与检测资料。',
    form_quantity: '预计数量', form_color: '颜色 / RAL 色号', form_size: '屋面尺寸 / 板长', form_port: '目的港',
    applications_heading: '屋面应用与工厂', applications_intro: '适用于住宅、商业、工业及农业屋面的产品选择。',
    applications_label: '应用场景', factory_label: '佛山工厂',
    whatsapp_cta: '通过 WhatsApp 联系', skip_main: '跳至主要内容'
  }
};
